apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: complai
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: complaiacr.azurecr.io/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_DIRECTUS_URL
          valueFrom:
            configMapKeyRef:
              name: complai-config
              key: NEXT_PUBLIC_DIRECTUS_URL
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            configMapKeyRef:
              name: complai-config
              key: NEXT_PUBLIC_APP_URL
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: wait-for-directus
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl -f http://directus-service:8055/server/ping; do echo waiting for directus; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: complai
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
