apiVersion: v1
kind: Secret
metadata:
  name: complai-secrets
  namespace: complai
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  # To encode: echo -n "your-secret" | base64
  postgres-password: cG9zdGdyZXMxMjM=  # postgres123
  directus-key: ZGlyZWN0dXMxMjM=        # directus123
  directus-secret: ZGlyZWN0dXMtc2VjcmV0LTEyMw==  # directus-secret-123
  jwt-secret: and0LXNlY3JldC0xMjM=      # jwt-secret-123
  access-token-ttl: MzYwMA==            # 3600
  refresh-token-ttl: NzI4MDA=           # 72800
